controller_list:
  - name: fake_my_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_my_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - ur5_finger_joint1
initial:  # Define initial robot poses per group
  - group: my_robot
    pose: hor
  - group: my_gripper
    pose: gripper_close