controller_list:
  - name: fake_ur5_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_panda_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - ur5_finger_joint1
initial:  # Define initial robot poses per group
  - group: ur5_robot
    pose: hor
  - group: panda_gripper
    pose: close